#ifndef __XBAR_H__
#define __XBAR_H__

#include "types.h"

#define XBAR_CONFIG_FAM(master, config_family) (master + (config_family * 0x10000))
#define XBAR_CONFIG_DEV(master, config_family, device) (XBAR_CONFIG_FAM(master, config_family) + (device * 0x400))
#define XBAR_CONFIG_REG(master, config_family, device, reg) (XBAR_CONFIG_DEV(master, config_family, device) + (reg * 4))

#define XBAR_F00D_BUS 0xE00C0000
#define XBAR_MAIN_XBAR 0xEC000000
#define XBAR_CENTER_XBAR 0xEC100000
#define XBAR_VIDEO_XBAR 0xEC200000
#define XBAR_IFTU_XBAR 0xEC300000
#define XBAR_VIP_XBAR 0xEC400000
#define XBAR_DEBUG_BUS 0xEC500000
#define XBAR_DMAC_XBAR 0xEC600000
#define XBAR_IO_SLAVE_BUS 0xED000000
#define XBAR_IO_MASTER_BUS 0xED100000
#define XBAR_PERVASIVE_BUS 0xED200000
#define XBAR_MISC_IO_BUS 0xED300000
#define XBAR_NORTH_IO_MASTER_BUS 0xED400000
#define XBAR_AUDIO_BUS 0xED500000
#define XBAR_NORTH_IO_SLAVE_BUS 0xED600000
#define XBAR_SRC_BUS 0xED700000
#define XBAR_GPU_REG_BUS 0xED800000
#define XBAR_IFTU_REG_BUS 0xED900000
#define XBAR_CAMERA_SLAVE_BUS 0xEE000000
#define XBAR_CAMERA_MASTER_BUS 0xEE100000
#define XBAR_USB_SLAVE_BUS 0xEE200000
#define XBAR_USB_MASTER_BUS 0xEE300000
#define XBAR_SUBLCD_SLAVE_BUS 0xEE400000
#define XBAR_SUBLCD_MASTER_BUS 0xEE500000
#define XBAR_CAMERA_REG_BUS 0xEE600000

enum XBAR_CONFIG_FAMILIES {
    XBAR_CFG_FAMILY_F00D_CUSTOM = 0, // only for XBAR_F00D_BUS
    XBAR_CFG_FAMILY_ROUTE_CONTROL = 5,
    XBAR_CFG_FAMILY_ACCESS_CONTROL
};

enum XBAR_ROUTE_CONTROL_REGISTERS {
    XBAR_ROUTE_CONTROL_SWITCH = 8
};

enum XBAR_ACCESS_CONTROL_REGISTERS {
    XBAR_ACCESS_CONTROL_WHITELIST = 18
};

#define XBAR_DEV_UNK48 48

enum XBAR_MAIN_DEVICES {
    XBAR_MXB_DEV_SPAD32K,
    XBAR_MXB_DEV_LPDDR0,
    XBAR_MXB_DEV_ACP,
    XBAR_MXB_DEV_CENTER_XBAR0 = 32,
    XBAR_MXB_DEV_CENTER_XBAR1,
    XBAR_MXB_DEV_IO_SLAVE_BUS
};

enum XBAR_CENTER_DEVICES {
    XBAR_CXB_DEV_TACHYON_EDRAM,
    XBAR_CXB_DEV_DEVNULL,
    XBAR_CXB_DEV_GPU_XBAR,
    XBAR_CXB_DEV_MXB0 = 32,
    XBAR_CXB_DEV_MXB1,
    XBAR_CXB_DEV_MXB2,
    XBAR_CXB_DEV_VXB
};

enum XBAR_VIDEO_DEVICES {
    XBAR_VIDXB_DEV_SPAD128K,
    XBAR_VIDXB_DEV_GPUXB0,
    XBAR_VIDXB_DEV_GPUXB1,
    XBAR_VIDXB_DEV_GPUXB2,
    XBAR_VIDXB_DEV_CXB0 = 32,
    XBAR_VIDXB_DEV_CXB1,
    XBAR_VIDXB_DEV_DEBUG_BUS
};

enum XBAR_IFTU_DEVICES {
    XBAR_IFTUXB_DEV_UNK0,
    XBAR_IFTUXB_DEV_VIDXB0 = 32,
    XBAR_IFTUXB_DEV_VIDXB1
};

enum XBAR_VIP_DEVICES {
    XBAR_VIPXB_DEV_GPUXB,
    XBAR_VIPXB_DEV_VIDXB0 = 32,
    XBAR_VIPXB_DEV_VIDXB1
};

enum XBAR_DEBUG_DEVICES {
    XBAR_DBG_BUS_DEV_SDIO0,
    XBAR_DBG_BUS_DEV_SDIO1,
    XBAR_DBG_BUS_DEV_LPDDR1,
    XBAR_DBG_BUS_DEV_VIDXB = 32
};

enum XBAR_DMAC_DEVICES {
    XBAR_DMACXB_DEV_MXB0 = 32,
    XBAR_DMACXB_DEV_MXB1,
    XBAR_DMACXB_DEV_CXB0,
    XBAR_DMACXB_DEV_CXB1
};

enum XBAR_IO_SLAVE_DEVICES {
    XBAR_SIO_BUS_DEV_PERVASIVE_BUS = 32,
    XBAR_SIO_BUS_DEV_NORTH_IO_BUS,
    XBAR_SIO_BUS_DEV_GPU_REG_BUS,
    XBAR_SIO_BUS_DEV_MISC_IO_BUS,
    XBAR_SIO_BUS_DEV_CAMERA_SLAVE_BUS0,
    XBAR_SIO_BUS_DEV_CAMERA_SLAVE_BUS1,
    XBAR_SIO_BUS_DEV_CAMERA_SLAVE_BUS2,
    XBAR_SIO_BUS_DEV_MIO_BUS,
    XBAR_SIO_BUS_DEV_DMACXB
};

enum XBAR_IO_MASTER_DEVICES {
    XBAR_MIO_BUS_DEV_MXB = 32,
    XBAR_MIO_BUS_DEV_CXB
};

enum XBAR_PERVASIVE_DEVICES {
    XBAR_PERV_BUS_DEV_DMAC0,
    XBAR_PERV_BUS_DEV_DMAC1,
    XBAR_PERV_BUS_DEV_PERVASIVE,
    XBAR_PERV_BUS_DEV_CORESIGHT,
    XBAR_PERV_BUS_DEV_VFPINT
};

enum XBAR_IO_MISC_DEVICES {
    XBAR_MISC_BUS_DEV_UART0,
    XBAR_MISC_BUS_DEV_UART1,
    XBAR_MISC_BUS_DEV_UART2,
    XBAR_MISC_BUS_DEV_UART3,
    XBAR_MISC_BUS_DEV_UART4,
    XBAR_MISC_BUS_DEV_UART5,
    XBAR_MISC_BUS_DEV_UART6,
    XBAR_MISC_BUS_DEV_GPIO0,
    XBAR_MISC_BUS_DEV_TIMER,
    XBAR_MISC_BUS_DEV_PWM
};

enum XBAR_NORTH_IO_MASTER_DEVICES {
    XBAR_NORTH_MIO_BUS_DEV_KEYRING,
    XBAR_NORTH_MIO_BUS_DEV_AUDIO_BUS = 32,
    XBAR_NORTH_MIO_BUS_DEV_SRC_BUS,
    XBAR_NORTH_MIO_BUS_DEV_MIO_BUS0,
    XBAR_NORTH_MIO_BUS_DEV_MIO_BUS1
};

enum XBAR_AUDIO_DEVICES {
    XBAR_AUDIO_BUS_DEV_I2S0,
    XBAR_AUDIO_BUS_DEV_I2S1,
    XBAR_AUDIO_BUS_DEV_I2S2,
    XBAR_AUDIO_BUS_DEV_I2S3,
    XBAR_AUDIO_BUS_DEV_I2S4,
    XBAR_AUDIO_BUS_DEV_I2S5,
    XBAR_AUDIO_BUS_DEV_I2S6,
    XBAR_AUDIO_BUS_DEV_I2S7,
    XBAR_AUDIO_BUS_DEV_SPDIF
};

enum XBAR_NORTH_IO_SLAVE_DEVICES {
    XBAR_NORTH_SIO_BUS_DEV_DMAC4,
    XBAR_NORTH_SIO_BUS_DEV_DMAC5,
    XBAR_NORTH_SIO_BUS_DEV_I2C0,
    XBAR_NORTH_SIO_BUS_DEV_I2C1,
    XBAR_NORTH_SIO_BUS_DEV_HSMMC1,
    XBAR_NORTH_SIO_BUS_DEV_HSMMC2,
    XBAR_NORTH_SIO_BUS_DEV_HSMMC3,
    XBAR_NORTH_SIO_BUS_DEV_NORTH_MIO_BUS = 32
};

enum XBAR_SRC_DEVICES {
    XBAR_SRC_BUS_DEV_SRC0,
    XBAR_SRC_BUS_DEV_SRC1,
    XBAR_SRC_BUS_DEV_SRC2,
    XBAR_SRC_BUS_DEV_SRC3
};

enum XBAR_GPU_REG_DEVICES {
    XBAR_GPU_REG_BUS_DEV_DMAC2,
    XBAR_GPU_REG_BUS_DEV_DMAC3,
    XBAR_GPU_REG_BUS_DEV_LCD_DMAC,
    XBAR_GPU_REG_BUS_DEV_DMAC6,
    XBAR_GPU_REG_BUS_DEV_PA,
    XBAR_GPU_REG_BUS_DEV_PERVASIVE2,
    XBAR_GPU_REG_BUS_DEV_SONY_REG_BUS,
    XBAR_GPU_REG_BUS_DEV_IFTU_REG_BUS = 32,
    XBAR_GPU_REG_BUS_DEV_VIPXB
};

enum XBAR_IFTU_REG_DEVICES {
    XBAR_IFTU_REG_BUS_DEV_IFTU0,
    XBAR_IFTU_REG_BUS_DEV_IFTU1,
    XBAR_IFTU_REG_BUS_DEV_IFTU2,
    XBAR_IFTU_REG_BUS_DEV_DSI0,
    XBAR_IFTU_REG_BUS_DEV_DSI1,
    XBAR_IFTU_REG_BUS_DEV_IFTUXB = 32
};

enum XBAR_CAMERA_SLAVE_DEVICES {
    XBAR_SCAM_BUS_DEV_GPIO1,
    XBAR_SCAM_BUS_DEV_UNK1,
    XBAR_SCAM_BUS_DEV_CAM_REG_BUS = 32,
    XBAR_SCAM_BUS_DEV_SLCD_SLAVE_BUS0,
    XBAR_SCAM_BUS_DEV_USB_SLAVE_BUS,
    XBAR_SCAM_BUS_DEV_SLCD_SLAVE_BUS1,
    XBAR_SCAM_BUS_DEV_CAM_MASTER_BUS
};

enum XBAR_CAMERA_MASTER_DEVICES {
    XBAR_MCAM_BUS_DEV_MIO_BUS0 = 32,
    XBAR_MCAM_BUS_DEV_MIO_BUS1
};

enum XBAR_USB_SLAVE_DEVICES {
    XBAR_SUSB_BUS_DEV_USB0_OTG,
    XBAR_SUSB_BUS_DEV_USB1_HOST,
    XBAR_SUSB_BUS_DEV_USB2_HOST,
    XBAR_SUSB_BUS_DEV_USB1_DEVICE0,
    XBAR_SUSB_BUS_DEV_USB1_DEVICE1,
    XBAR_SUSB_BUS_DEV_USB1_DEVICE2,
    XBAR_SUSB_BUS_DEV_USB1_DEVICE3,
    XBAR_SUSB_BUS_DEV_USB2_DEVICE0,
    XBAR_SUSB_BUS_DEV_USB2_DEVICE1,
    XBAR_SUSB_BUS_DEV_USB2_DEVICE2,
    XBAR_SUSB_BUS_DEV_USB2_DEVICE3,
    XBAR_SUSB_BUS_DEV_UNKB,
    XBAR_SUSB_BUS_DEV_UNKC,
    XBAR_SUSB_BUS_DEV_UNKD,
    XBAR_SUSB_BUS_DEV_USB_MASTER_BUS = 32
};

enum XBAR_USB_MASTER_DEVICES {
    XBAR_MUSB_BUS_DEV_MCAM_BUS = 32
};

enum XBAR_SUBLCD_SLAVE_DEVICES {
    XBAR_SLCD_SLAVE_BUS_DEV_HSMMC0,
    XBAR_SLCD_SLAVE_BUS_DEV_SLCD,
    XBAR_SLCD_SLAVE_BUS_DEV_SMSHC,
    XBAR_SLCD_SLAVE_BUS_DEV_SPI0,
    XBAR_SLCD_SLAVE_BUS_DEV_SPI1,
    XBAR_SLCD_SLAVE_BUS_DEV_SPI2,
    XBAR_SLCD_SLAVE_BUS_DEV_SLCD_MASTER_BUS = 32
};

enum XBAR_SUBLCD_MASTER_DEVICES {
    XBAR_SLCD_MASTER_BUS_DEV_MCAM_BUS = 32
};

enum XBAR_CAMERA_REG_DEVICES {
    XBAR_CAM_REG_BUS_DEV_CAM_IF0,
    XBAR_CAM_REG_BUS_DEV_CAM_IF1,
    XBAR_CAM_REG_BUS_DEV_CSI0,
    XBAR_CAM_REG_BUS_DEV_CSI1
};

#endif