#ifndef __XBAR_H__
#define __XBAR_H__

#include "types.h"
#include "paddr.h"

#define XBAR_FAMILY_SIZE 0x10000
#define XBAR_DEVICE_SIZE 0x400

#define XBAR_CONFIG_FAM(master, config_family) (master ## _OFFSET + (config_family * XBAR_FAMILY_SIZE))
#define XBAR_CONFIG_DEV(master, config_family, device) (XBAR_CONFIG_FAM(master, config_family) + (device * XBAR_DEVICE_SIZE))
#define XBAR_CONFIG_REG(master, config_family, device, reg) (XBAR_CONFIG_DEV(master, config_family, device) + (reg * sizeof(uint32_t)))

/*
IA - can initiate bus transfer?
TA - can be targeted by a bus transfer?
*/
enum XBAR_CONFIG_FAMILIES {
    XBAR_CFG_FAMILY_IA = 4,
    XBAR_CFG_FAMILY_TA = 5, // prev: XBAR_CFG_FAMILY_ROUTE_CONTROL
    XBAR_CFG_FAMILY_ACCESS_CONTROL
};

enum XBAR_TA_REGISTERS {
    XBAR_TA_ROUTE_CONTROL_SWITCH = 8
};

enum XBAR_ACCESS_CONTROL_REGISTERS {
    XBAR_ACCESS_CONTROL_WHITELIST = 18
};

#define MAIN_XBAR MAIN_XBAR
enum XBAR_TA_MAIN_DEVICES {
    XBAR_TA_MXB_DEV_SPAD32K,
    XBAR_TA_MXB_DEV_LPDDR0,
    XBAR_TA_MXB_DEV_ACP,
    XBAR_TA_MXB_DEV_CENTER_XBAR0 = 32,
    XBAR_TA_MXB_DEV_CENTER_XBAR1,
    XBAR_TA_MXB_DEV_IO_SLAVE_BUS,
    XBAR_TA_MXB_DEV_DMAC_XBAR0
};

enum XBAR_IA_MAIN_DEVICES {
    XBAR_IA_MXB_DEV_ARM0,
    XBAR_IA_MXB_DEV_ARM1,
    XBAR_IA_MXB_DEV_CENTER_XBAR0 = 32,
    XBAR_IA_MXB_DEV_CENTER_XBAR1,
    XBAR_IA_MXB_DEV_IO_MASTER_BUS,
    XBAR_IA_MXB_DEV_DMAC_XBAR0,
    XBAR_IA_MXB_DEV_DMAC_XBAR1
};

#define CENTER_XBAR CENTER_XBAR
enum XBAR_TA_CENTER_DEVICES {
    XBAR_TA_CXB_DEV_TACHYON_EDRAM,
    XBAR_TA_CXB_DEV_DEVNULL,
    XBAR_TA_CXB_DEV_GPU_XBAR,
    XBAR_TA_CXB_DEV_MXB0 = 32,
    XBAR_TA_CXB_DEV_MXB1,
    XBAR_TA_CXB_DEV_MXB2,
    XBAR_TA_CXB_DEV_VIDXB
};

enum XBAR_IA_CENTER_DEVICES {
    XBAR_IA_CXB_DEV_GPU_XBAR,
    XBAR_IA_CXB_DEV_MXB0 = 32,
    XBAR_IA_CXB_DEV_MXB1,
    XBAR_IA_CXB_DEV_VIDXB0,
    XBAR_IA_CXB_DEV_VIDXB1,
    XBAR_IA_CXB_DEV_MIO_BUS,
    XBAR_IA_CXB_DEV_DMAC_XBAR0,
    XBAR_IA_CXB_DEV_DMAC_XBAR1
};

#define VIDEO_XBAR VIDEO_XBAR
enum XBAR_TA_VIDEO_DEVICES {
    XBAR_TA_VIDXB_DEV_SPAD128K,
    XBAR_TA_VIDXB_DEV_GPUXB0,
    XBAR_TA_VIDXB_DEV_GPUXB1,
    XBAR_TA_VIDXB_DEV_GPUXB2,
    XBAR_TA_VIDXB_DEV_CXB0 = 32,
    XBAR_TA_VIDXB_DEV_CXB1,
    XBAR_TA_VIDXB_DEV_DEBUG_BUS
};

enum XBAR_IA_VIDEO_DEVICES {
    XBAR_IA_VIDXB_DEV_DMAC2,
    XBAR_IA_VIDXB_DEV_DMAC3,
    XBAR_IA_VIDXB_DEV_VNZ,
    XBAR_IA_VIDXB_DEV_LCDDMAC,
    XBAR_IA_VIDXB_DEV_CXB = 32,
    XBAR_IA_VIDXB_DEV_IFTUXB0,
    XBAR_IA_VIDXB_DEV_IFTUXB1,
    XBAR_IA_VIDXB_DEV_VIPB0,
    XBAR_IA_VIDXB_DEV_VIPXB1,
    XBAR_IA_VIDXB_DEV_DEBUG_BUS
};

#define IFTU_XBAR IFTU_XBAR
enum XBAR_TA_IFTU_DEVICES {
    XBAR_TA_IFTUXB_DEV_VIDXB0 = 32,
    XBAR_TA_IFTUXB_DEV_VIDXB1
};

enum XBAR_IA_IFTU_DEVICES {
    XBAR_IA_IFTUXB_DEV_IFTU0A,
    XBAR_IA_IFTUXB_DEV_IFTU0B,
    XBAR_IA_IFTUXB_DEV_IFTU1A,
    XBAR_IA_IFTUXB_DEV_IFTU1B,
    XBAR_IA_IFTUXB_DEV_IFTU2,
    XBAR_IA_IFTUXB_DEV_IFTUREGBUS = 32
};

#define VIP_XBAR VIP_XBAR
enum XBAR_TA_VIP_DEVICES {
    XBAR_TA_VIPXB_DEV_GPUXB,
    XBAR_TA_VIPXB_DEV_VIDXB0 = 32,
    XBAR_TA_VIPXB_DEV_VIDXB1
};

enum XBAR_IA_VIP_DEVICES {
    XBAR_IA_VIPXB_DEV_VDP0,
    XBAR_IA_VIPXB_DEV_VDP1,
    XBAR_IA_VIPXB_DEV_VDP2,
    XBAR_IA_VIPXB_DEV_VDP3,
    XBAR_IA_VIPXB_DEV_VDPMEP,
    XBAR_IA_VIPXB_DEV_BAPMEP,
    XBAR_IA_VIPXB_DEV_GPUREGBUS = 32
};

#define DEBUG_BUS DEBUG_BUS
enum XBAR_TA_DEBUG_DEVICES {
    XBAR_TA_DBG_BUS_DEV_SDIO0,
    XBAR_TA_DBG_BUS_DEV_SDIO1,
    XBAR_TA_DBG_BUS_DEV_LPDDR1,
    XBAR_TA_DBG_BUS_DEV_VIDXB = 32
};

enum XBAR_IA_DEBUG_DEVICES {
    XBAR_IA_DBG_BUS_DEV_DMAC6,
    XBAR_IA_DBG_BUS_DEV_PA,
    XBAR_IA_DBG_BUS_DEV_VIDXB = 32
};

#define DMAC_XBAR DMAC_XBAR
enum XBAR_TA_DMAC_DEVICES {
    XBAR_TA_DMACXB_DEV_MXB0 = 32,
    XBAR_TA_DMACXB_DEV_MXB1,
    XBAR_TA_DMACXB_DEV_CXB0,
    XBAR_TA_DMACXB_DEV_CXB1
};

enum XBAR_IA_DMAC_DEVICES {
    XBAR_IA_DMACXB_DEV_DMAC0,
    XBAR_IA_DMACXB_DEV_DMAC1,
    XBAR_IA_DMACXB_DEV_SIOBUS = 32
};

#define IO_SLAVE_BUS IO_SLAVE_BUS
enum XBAR_TA_IO_SLAVE_DEVICES {
    XBAR_TA_SIO_BUS_DEV_PERVASIVE_BUS = 32,
    XBAR_TA_SIO_BUS_DEV_NORTH_IO_BUS,
    XBAR_TA_SIO_BUS_DEV_GPU_REG_BUS,
    XBAR_TA_SIO_BUS_DEV_MISC_IO_BUS,
    XBAR_TA_SIO_BUS_DEV_CAMERA_SLAVE_BUS0,
    XBAR_TA_SIO_BUS_DEV_CAMERA_SLAVE_BUS1,
    XBAR_TA_SIO_BUS_DEV_CAMERA_SLAVE_BUS2,
    XBAR_TA_SIO_BUS_DEV_MIO_BUS,
    XBAR_TA_SIO_BUS_DEV_DMACXB
};

enum XBAR_IA_IO_SLAVE_DEVICES {
    XBAR_IA_SIO_BUS_DEV_MXB = 32
};

#define IO_MASTER_BUS IO_MASTER_BUS
enum XBAR_TA_IO_MASTER_DEVICES {
    XBAR_TA_MIO_BUS_DEV_MXB = 32,
    XBAR_TA_MIO_BUS_DEV_CXB
};

enum XBAR_IA_IO_MASTER_DEVICES {
    XBAR_IA_MIO_BUS_DEV_NIOBUS = 32,
    XBAR_IA_MIO_BUS_DEV_MCAMBUS,
    XBAR_IA_MIO_BUS_DEV_SIOBUS
};

#define PERVASIVE_BUS PERVASIVE_BUS
enum XBAR_TA_PERVASIVE_DEVICES {
    XBAR_TA_PERV_BUS_DEV_DMAC0,
    XBAR_TA_PERV_BUS_DEV_DMAC1,
    XBAR_TA_PERV_BUS_DEV_PERVASIVE,
    XBAR_TA_PERV_BUS_DEV_CORESIGHT,
    XBAR_TA_PERV_BUS_DEV_VFPINT
};

enum XBAR_IA_PERVASIVE_DEVICES {
    XBAR_IA_PERV_BUS_DEV_SIOBUS = 32
};

#define MISC_IO_BUS MISC_IO_BUS
enum XBAR_TA_IO_MISC_DEVICES {
    XBAR_TA_MISC_BUS_DEV_UART0,
    XBAR_TA_MISC_BUS_DEV_UART1,
    XBAR_TA_MISC_BUS_DEV_UART2,
    XBAR_TA_MISC_BUS_DEV_UART3,
    XBAR_TA_MISC_BUS_DEV_UART4,
    XBAR_TA_MISC_BUS_DEV_UART5,
    XBAR_TA_MISC_BUS_DEV_UART6,
    XBAR_TA_MISC_BUS_DEV_GPIO0,
    XBAR_TA_MISC_BUS_DEV_TIMER,
    XBAR_TA_MISC_BUS_DEV_PWM
};

enum XBAR_IA_IO_MISC_DEVICES {
    XBAR_IA_MISC_BUS_DEV_SIOBUS = 32
};

#define NORTH_IO_MASTER_BUS NIO_MASTER_BUS
enum XBAR_TA_NORTH_IO_MASTER_DEVICES {
    XBAR_TA_NORTH_MIO_BUS_DEV_KEYRING,
    XBAR_TA_NORTH_MIO_BUS_DEV_AUDIO_BUS = 32,
    XBAR_TA_NORTH_MIO_BUS_DEV_SRC_BUS,
    XBAR_TA_NORTH_MIO_BUS_DEV_MIO_BUS0,
    XBAR_TA_NORTH_MIO_BUS_DEV_MIO_BUS1
};

enum XBAR_IA_NORTH_IO_MASTER_DEVICES {
    XBAR_IA_NORTH_MIO_BUS_DEV_DMAC4,
    XBAR_IA_NORTH_MIO_BUS_DEV_DMAC5,
    XBAR_IA_NORTH_MIO_BUS_DEV_HSMMC1,
    XBAR_IA_NORTH_MIO_BUS_DEV_HSMMC2,
    XBAR_IA_NORTH_MIO_BUS_DEV_HSMMC3,
    XBAR_IA_NORTH_MIO_BUS_DEV_NORTH_SIOBUS = 32
};

#define AUDIO_BUS AUDIO_BUS
enum XBAR_TA_AUDIO_DEVICES {
    XBAR_TA_AUDIO_BUS_DEV_I2S0,
    XBAR_TA_AUDIO_BUS_DEV_I2S1,
    XBAR_TA_AUDIO_BUS_DEV_I2S2,
    XBAR_TA_AUDIO_BUS_DEV_I2S3,
    XBAR_TA_AUDIO_BUS_DEV_I2S4,
    XBAR_TA_AUDIO_BUS_DEV_I2S5,
    XBAR_TA_AUDIO_BUS_DEV_I2S6,
    XBAR_TA_AUDIO_BUS_DEV_I2S7,
    XBAR_TA_AUDIO_BUS_DEV_SPDIF
};

enum XBAR_IA_AUDIO_DEVICES {
    XBAR_IA_AUDIO_BUS_DEV_NORTH_MIOBUS = 32
};

#define NORTH_IO_SLAVE_BUS NIO_SLAVE_BUS
enum XBAR_TA_NORTH_IO_SLAVE_DEVICES {
    XBAR_TA_NORTH_SIO_BUS_DEV_DMAC4,
    XBAR_TA_NORTH_SIO_BUS_DEV_DMAC5,
    XBAR_TA_NORTH_SIO_BUS_DEV_I2C0,
    XBAR_TA_NORTH_SIO_BUS_DEV_I2C1,
    XBAR_TA_NORTH_SIO_BUS_DEV_HSMMC1,
    XBAR_TA_NORTH_SIO_BUS_DEV_HSMMC2,
    XBAR_TA_NORTH_SIO_BUS_DEV_HSMMC3,
    XBAR_TA_NORTH_SIO_BUS_DEV_NORTH_MIO_BUS = 32
};

enum XBAR_IA_NORTH_IO_SLAVE_DEVICES {
    XBAR_IA_NORTH_SIO_BUS_DEV_SIOBUS = 32
};

#define SRC_BUS SRC_BUS
enum XBAR_TA_SRC_DEVICES {
    XBAR_TA_SRC_BUS_DEV_SRC0,
    XBAR_TA_SRC_BUS_DEV_SRC1,
    XBAR_TA_SRC_BUS_DEV_SRC2,
    XBAR_TA_SRC_BUS_DEV_SRC3 // not present in ES4
};

enum XBAR_IA_SRC_DEVICES {
    XBAR_IA_SRC_BUS_DEV_NORTH_MIOBUS = 32
};

#define GPU_REG_BUS GPU_REG_BUS
enum XBAR_TA_GPU_REG_DEVICES {
    XBAR_TA_GPU_REG_BUS_DEV_DMAC2,
    XBAR_TA_GPU_REG_BUS_DEV_DMAC3,
    XBAR_TA_GPU_REG_BUS_DEV_LCD_DMAC,
    XBAR_TA_GPU_REG_BUS_DEV_DMAC6,
    XBAR_TA_GPU_REG_BUS_DEV_PA,
    XBAR_TA_GPU_REG_BUS_DEV_PERVASIVE2,
    XBAR_TA_GPU_REG_BUS_DEV_SONY_REG_BUS,
    XBAR_TA_GPU_REG_BUS_DEV_IFTU_REG_BUS = 32,
    XBAR_TA_GPU_REG_BUS_DEV_VIPXB
};

enum XBAR_IA_GPU_REG_DEVICES {
    XBAR_IA_GPU_REG_BUS_DEV_SIOBUS = 32
};

#define IFTU_REG_BUS IFTU_REG_BUS
enum XBAR_TA_IFTU_REG_DEVICES {
    XBAR_TA_IFTU_REG_BUS_DEV_IFTU0,
    XBAR_TA_IFTU_REG_BUS_DEV_IFTU1,
    XBAR_TA_IFTU_REG_BUS_DEV_IFTU2,
    XBAR_TA_IFTU_REG_BUS_DEV_DSI0,
    XBAR_TA_IFTU_REG_BUS_DEV_DSI1,
    XBAR_TA_IFTU_REG_BUS_DEV_IFTUXB = 32
};

enum XBAR_IA_IFTU_REG_DEVICES {
    XBAR_IA_IFTU_REG_BUS_DEV_GPU_REGBUS = 32
};

#define CAMERA_SLAVE_BUS CAM_SLAVE_BUS
enum XBAR_TA_CAMERA_SLAVE_DEVICES {
    XBAR_TA_SCAM_BUS_DEV_GPIO1,
    XBAR_TA_SCAM_BUS_DEV_CAM_REG_BUS = 32,
    XBAR_TA_SCAM_BUS_DEV_SLCD_SLAVE_BUS0,
    XBAR_TA_SCAM_BUS_DEV_USB_SLAVE_BUS,
    XBAR_TA_SCAM_BUS_DEV_SLCD_SLAVE_BUS1,
    XBAR_TA_SCAM_BUS_DEV_CAM_MASTER_BUS
};

enum XBAR_IA_CAMERA_SLAVE_DEVICES {
    XBAR_IA_SCAM_BUS_DEV_SIOBUS0 = 32,
    XBAR_IA_SCAM_BUS_DEV_SIOBUS1,
    XBAR_IA_SCAM_BUS_DEV_SIOBUS2
};

#define CAMERA_MASTER_BUS CAM_MASTER_BUS
enum XBAR_TA_CAMERA_MASTER_DEVICES {
    XBAR_TA_MCAM_BUS_DEV_MIO_BUS0 = 32,
    XBAR_TA_MCAM_BUS_DEV_MIO_BUS1
};

enum XBAR_IA_CAMERA_MASTER_DEVICES {
    XBAR_IA_MCAM_BUS_DEV_CIF0,
    XBAR_IA_MCAM_BUS_DEV_CIF1,
    XBAR_IA_MCAM_BUS_DEV_MSLCDBUS = 32,
    XBAR_IA_MCAM_BUS_DEV_MUSBBUS,
    XBAR_IA_MCAM_BUS_DEV_SCAMBUS
};

#define USB_SLAVE_BUS USB_SLAVE_BUS
enum XBAR_TA_USB_SLAVE_DEVICES {
    XBAR_TA_SUSB_BUS_DEV_USB0_OTG,
    XBAR_TA_SUSB_BUS_DEV_USB1_HOST,
    XBAR_TA_SUSB_BUS_DEV_USB2_HOST,
    XBAR_TA_SUSB_BUS_DEV_USB1_DEVICE0,
    XBAR_TA_SUSB_BUS_DEV_USB1_DEVICE1,
    XBAR_TA_SUSB_BUS_DEV_USB1_DEVICE2,
    XBAR_TA_SUSB_BUS_DEV_USB1_DEVICE3,
    XBAR_TA_SUSB_BUS_DEV_USB2_DEVICE0,
    XBAR_TA_SUSB_BUS_DEV_USB2_DEVICE1,
    XBAR_TA_SUSB_BUS_DEV_USB2_DEVICE2,
    XBAR_TA_SUSB_BUS_DEV_USB2_DEVICE3,
    XBAR_TA_SUSB_BUS_DEV_USB_MASTER_BUS = 32
};

enum XBAR_IA_USB_SLAVE_DEVICES {
    XBAR_IA_SUSB_BUS_DEV_SCAMBUS = 32
};

#define USB_MASTER_BUS
enum XBAR_TA_USB_MASTER_DEVICES {
    XBAR_TA_MUSB_BUS_DEV_MCAM_BUS = 32
};

enum XBAR_IA_USB_MASTER_DEVICES {
    XBAR_IA_MUSB_BUS_DEV_UNK, // TODO
    XBAR_IA_MUSB_BUS_DEV_USB1_OHCI,
    XBAR_IA_MUSB_BUS_DEV_USB1_EHCI,
    XBAR_IA_MUSB_BUS_DEV_USB2_OHCI,
    XBAR_IA_MUSB_BUS_DEV_USB2_EHCI,
    XBAR_IA_MUSB_BUS_DEV_USB0_OHCI,
    XBAR_IA_MUSB_BUS_DEV_USB0_EHCI,
    XBAR_IA_MUSB_BUS_DEV_USB1_DEV,
    XBAR_IA_MUSB_BUS_DEV_USB2_DEV,
    XBAR_IA_MUSB_BUS_DEV_USB0_DEV,
    XBAR_IA_MUSB_BUS_DEV_SUSBUS = 32
};

#define SUBLCD_SLAVE_BUS SLCD_SLAVE_BUS
enum XBAR_TA_SUBLCD_SLAVE_DEVICES {
    XBAR_TA_SLCD_SLAVE_BUS_DEV_HSMMC0,
    XBAR_TA_SLCD_SLAVE_BUS_DEV_SLCD,
    XBAR_TA_SLCD_SLAVE_BUS_DEV_SMSHC,
    XBAR_TA_SLCD_SLAVE_BUS_DEV_SPI0,
    XBAR_TA_SLCD_SLAVE_BUS_DEV_SPI1,
    XBAR_TA_SLCD_SLAVE_BUS_DEV_SPI2,
    XBAR_TA_SLCD_SLAVE_BUS_DEV_SLCD_MASTER_BUS = 32
};

enum XBAR_IA_SUBLCD_SLAVE_DEVICES {
    XBAR_IA_SLCD_SLAVE_BUS_DEV_SCAMBUS0 = 32,
    XBAR_IA_SLCD_SLAVE_BUS_DEV_SCAMBUS1
};

#define SUBLCD_MASTER_BUS SLCD_MASTER_BUS
enum XBAR_TA_SUBLCD_MASTER_DEVICES {
    XBAR_TA_SLCD_MASTER_BUS_DEV_MCAM_BUS = 32
};

enum XBAR_IA_SUBLCD_MASTER_DEVICES {
    XBAR_IA_SLCD_MASTER_BUS_DEV_HSMMC0,
    XBAR_IA_SLCD_MASTER_BUS_DEV_SLCD,
    XBAR_IA_SLCD_MASTER_BUS_DEV_SMSHC,
    XBAR_IA_SLCD_MASTER_BUS_DEV_SSLCDBUS = 32
};

#define CAMERA_REG_BUS CAM_REG_BUS
enum XBAR_TA_CAMERA_REG_DEVICES {
    XBAR_TA_CAM_REG_BUS_DEV_CAM_IF0,
    XBAR_TA_CAM_REG_BUS_DEV_CAM_IF1,
    XBAR_TA_CAM_REG_BUS_DEV_CSI0,
    XBAR_TA_CAM_REG_BUS_DEV_CSI1
};

enum XBAR_IA_CAMERA_REG_DEVICES {
    XBAR_IA_CAM_REG_BUS_DEV_SCAMBUS = 32
};

#endif