/* Generated by the Makefile, do not touch! */
INCLUDE psp2ref/misc/map.x; /* address space map */
cfg_PROG_load_addr = 0x0080B000;
cfg_PROG_uses_end = 0x820000;
cfg_sp_addr = cfg_PROG_uses_end;
cfg_sp_size = 0x2000;
cfg_PROG_load_end = cfg_sp_addr - cfg_sp_size;
cfg_PROG_max_size = 77824;
cfg_gp_addr = PROG_sdastart + 0x8000;
cfg_tp_addr = cfg_PROG_load_end;
