ifndef BOB_LP
	BOB_LP=0x00040000
endif
ifndef BOB_FP
	BOB_FP=0xA000
endif
ifndef BOB_SS
	BOB_SS=0x00002000
endif
BOB_END_ADDR=$(shell printf "0x%X" $$(($(BOB_LP) + $(BOB_FP))))
BOB_MAX_SIZE=$(shell printf "%d" $$(($(BOB_FP) - $(BOB_SS))))

SCE_SM_START=0xA000# static for release fws, will warn if bob is bigger
GPREL_REACH=0x8000# const for mep, gp will be dynamic if size > (2 * GPREL_REACH)

PSP2REF_DIR=psp2ref
LINKCFG_FILE=cfg.x

PREFIX=mep-elf-
CC=$(PREFIX)gcc
ADDEFS=-I$(PSP2REF_DIR)
CFLAGS=-ml -Os -std=gnu99 -nostdlib -fno-builtin -fno-inline -fno-strict-aliasing -Wall -Wno-volatile-register-var -mtiny=32
LD=$(PREFIX)gcc
LDFLAGS=-Wl,-T linker.x -nodefaultlibs -nostdlib -nostartfiles -Wl,-Map=bob.map
OBJCOPY=$(PREFIX)objcopy
OBJCOPYFLAGS=

SRCS=$(wildcard source/*.c)
ASMS=$(wildcard source/*.s)
OBJ=$(SRCS:.c=.o) source/ex.ao source/vector.ao source/debug.ao source/util.ao
OBJ_GLITCH=$(SRCS:.c=.o) source/ex.ao source/glitch_vector.ao source/debug.ao source/util.ao

all: $(LINKCFG_FILE) output/bob.bin

%.o: %.c
	@echo "\033[0;35mMidASM:\033[0;33m $< -> $<.asm\033[0m"
	@$(CC) -S -o $@.asm $< $(CFLAGS) $(ADDEFS)
	@echo "\033[0;35mCompile:\033[0;33m $< -> $@\033[0m"
	@$(CC) -c -o $@ $< $(CFLAGS) $(ADDEFS)

%.ao: %.s
	@echo "\033[0;35mAssemble:\033[0;33m $< -> $@\033[0m"
	@$(CC) -c -o $@ $< $(CFLAGS) $(ADDEFS)

bob.elf: $(OBJ)
	@echo "\033[0;35mLink:\033[0;33m $^ -> $@\033[0m"
	@$(LD) -o $@ $^ $(LDFLAGS)

bob_glitch.elf: $(OBJ_GLITCH)
	@echo "\033[0;35mLink (glitch):\033[0;33m $^ -> $@\033[0m"
	@$(LD) -o $@ $^ $(LDFLAGS)

%.bin: %.elf
	@echo "\033[0;35mStrip:\033[0;33m $< -> $@\033[0m"
	@$(OBJCOPY) -O binary $< $@
	
output/bob.bin: bob.bin bob_glitch.bin
	@echo "\033[0;35mPost-compilation:\033[0;33m"
	@echo " | clean source dir"
	@-rm source/*.o
	@-rm source/*.ao
	@-rm -rf output
	@echo " | create output tree"
	@mkdir output
	@mkdir output/asm
	@echo " | midway assembly -> output"
	@mv source/*.asm output/asm/
	@echo " | bob (glitch) -> output"
	@mv bob_glitch.elf output/bob_glitch.elf
	@mv bob_glitch.bin output/bob_glitch.bin
	@echo " | create bob binary include"
	@echo static const > output/bob.bin.h
	@xxd -i $< >> output/bob.bin.h
	@echo " | create bob exports header"
	@readelf -sW bob.elf | awk '{if ($$5 == "GLOBAL" && ($$4 == "FUNC" || $$4 == "OBJECT")) printf("#define bob_%s_addr 0x%s\n", $$8, $$2)}' > output/bob_exports.h
	@echo " | create bob import assembly"
	@readelf -sW bob.elf | awk '{if ($$5 == "GLOBAL" && $$4 == "FUNC") printf(".global %s\n%s:\njmp 0x%s\n\n", $$8, $$8, $$2)}' > output/bob_import.s
	@echo " | create bob linker"
	@echo ".bob_linker : {" > output/bob_linker.x && readelf -sW bob.elf | awk '{if ($$5 == "GLOBAL" && ($$4 == "FUNC" || $$4 == "OBJECT")) printf("\t%s = 0x%s;\n", $$8, $$2)}' >> output/bob_linker.x && echo "}" >> output/bob_linker.x
	@mv $(LINKCFG_FILE) output/bob_cfg.x
# readelf -sW bob.elf | awk '{if ($$5 == "GLOBAL" && ($$4 == "FUNC" || $$4 == "OBJECT")) print $$8}' | while IFS= read -r entry; do def=$$(grep -whR $$entry source/include/ | grep -v -e "#define" | grep -i ";" | sed 's/extern //'); [ -z "$$def" ] || echo "$${def%??} = (void *)bob_"$$entry"_addr;"; done > output/bob_imports.c
	@echo " | bob (main) -> output"
	@mv bob.elf output/bob.elf
	@mv bob.bin output/bob.bin
	@mv bob.map output/bob.map
	@echo " | ensure bob fits (BOB_MAX_SIZE: $(BOB_MAX_SIZE))"
	@if [ $$(stat -c %s output/bob.bin) -gt $(BOB_MAX_SIZE) ]; then echo "\033[0;31m\nERROR: bob.bin is too large\033[0m"; exit 1; fi
	@if [ $$(stat -c %s output/bob_glitch.bin) -gt $(BOB_MAX_SIZE) ]; then echo "\033[0;31m\nERROR: bob_glitch.bin is too large\033[0m"; exit 1; fi
	@if [ $$(($(BOB_FP))) -gt $$(($(SCE_SM_START))) ]; then echo "\033[0;31mWARNING: Footprint (BOB_FP=$(BOB_FP)) exceeds SCE SM load offset ($(SCE_SM_START))\033[0m"; fi
	@echo "  \-> \033[0;32mall done\n\033[0m"

clean:
	-rm source/*.o
	-rm source/*.ao
	-rm source/*.asm
	-rm -rf output
	-rm $(LINKCFG_FILE)

# dynamic config because -Wl,--defsym was acting up
$(LINKCFG_FILE): $(PSP2REF_DIR)/misc/map.x
	@echo "\033[0;35mConfiguring in:\033[0;33m $@\033[0m"
	@echo "\033[0;36m | Load:\033[0;32m $(BOB_LP)\033[0m"
	@echo "\033[0;36m | Size:\033[0;32m $(BOB_MAX_SIZE)\033[0m"
	@echo "\033[0;36m | Stack:\033[0;32m $(BOB_SS)\033[0m"
	@echo "\033[0;36m  \-> Footprint:\033[0;32m $(BOB_FP)\033[0m"
	@echo "/* Generated by the Makefile, do not touch! */" > $@
	@echo "INCLUDE $(PSP2REF_DIR)/misc/map.x /* address space map */" >> $@
	@echo ".cfg : {" >> $@
	@echo "  cfg_PROG_load_off = $(BOB_LP);" >> $@
	@echo "  cfg_PROG_uses_end = $(BOB_END_ADDR);" >> $@
	@echo "  cfg_sp_addr = cfg_PROG_uses_end;" >> $@
	@echo "  cfg_sp_size = $(BOB_SS);" >> $@
	@echo "  cfg_PROG_load_end = cfg_sp_addr - cfg_sp_size;" >> $@
	@echo "  cfg_PROG_max_size = $(BOB_MAX_SIZE);" >> $@
	@if [ $$(($(BOB_MAX_SIZE))) -gt $$(($(GPREL_REACH) * 2)) ]; then echo "  cfg_gp_addr = PROG_sdastart + 0x2000;" >> $@; else echo "  cfg_gp_addr = cfg_PROG_load_off + (cfg_PROG_max_size / 2);" >> $@; fi
	@echo "}" >> $@