/* Generated by the Makefile, do not touch! */
INCLUDE psp2ref/misc/map.x /* address space map */
.cfg : {
  cfg_PROG_load_off = 0x00040000;
  cfg_PROG_uses_end = 0x4A000;
  cfg_sp_addr = cfg_PROG_uses_end;
  cfg_sp_size = 0x00002000;
  cfg_PROG_load_end = cfg_sp_addr - cfg_sp_size;
  cfg_PROG_max_size = 32768;
  cfg_gp_addr = cfg_PROG_load_off + (cfg_PROG_max_size / 2);
}
